# Generated by Django 2.1.15 on 2020-06-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation_request',
            old_name='ngo_current_user_id',
            new_name='donation_request_user',
        ),
    ]
